## Step 1: download the Flight data from 2008

+ We're interested in predicting Departure Delays!

http://stat-computing.org/dataexpo/2009/the-data.html

In [1]:
import pandas as pd

df = pd.read_csv("/Users/Carter/Projects/DataScience/DS-SF-32/lessons/lesson-7/2008.csv").fillna(0)

In [2]:
pd.options.display.max_columns = 999

df.head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime UniqueCarrier  FlightNum TailNum  ActualElapsedTime  \
0        2225            WN        335  N712SW              128.0   
1        1000            WN       3231  N772SW              128.0   
2         750            WN        448  N428WN               96.0   
3        1100            WN       1746  N612SW               88.0   
4        1925            WN       3920  N464WN               90.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay Origin Dest  Distance  TaxiIn  \
0           150.0    116.0     -14.0       8.0    IAD  TPA       810     4.0   
1           145.0    113.0       2.0      19.0    IAD  TPA       810     5.0   
2            90.0     76.0      14.0       8.0    IND  BWI       515     3.0   
3            90.0     78.0      -6.0      -4.0    IND  BWI       515     3.0   
4            90.0     77.0      34.0      34.0    IND  BWI       515     3.0   

   TaxiOut  Cancelled CancellationCode  Diverted  CarrierDelay  WeatherDelay  \
0      8.0          0                0         0           0.0           0.0   
1     10.0          0                0         0           0.0           0.0   
2     17.0          0                0         0           0.0           0.0   
3      7.0          0                0         0           0.0           0.0   
4     10.0          0                0         0           2.0           0.0   

   NASDelay  SecurityDelay  LateAircraftDelay  
0       0.0            0.0                0.0  
1       0.0            0.0                0.0  
2       0.0            0.0                0.0  
3       0.0            0.0                0.0  
4       0.0            0.0               32.0

In [12]:
df2 = df.head(10000)

### This dataset is WAY TOO BIG for the get_dummies function

+ Feel free to test it out and eventually use the "interrupt" function when you get bored
+ Hey maybe it still works? Who knows. It took a while for me. 

In [ ]:
pd.get_dummies(df[['TailNum', 'Origin', 'Dest']])

### Let's first investigate the String Vars here

In [3]:
df[['UniqueCarrier', 'TailNum', 'Origin', 'Dest', 'CancellationCode']].head(10)

UniqueCarrier TailNum Origin Dest CancellationCode
0            WN  N712SW    IAD  TPA                0
1            WN  N772SW    IAD  TPA                0
2            WN  N428WN    IND  BWI                0
3            WN  N612SW    IND  BWI                0
4            WN  N464WN    IND  BWI                0
5            WN  N726SW    IND  JAX                0
6            WN  N763SW    IND  LAS                0
7            WN  N428WN    IND  LAS                0
8            WN  N689SW    IND  MCI                0
9            WN  N648SW    IND  MCI                0

## We can use the Label Encoder to map the Strings to numbers!

+ THESE ARE NOT DUMMY VARIABLES
+ Note the fit vs fit_transform function

In [10]:
from sklearn.preprocessing import  LabelEncoder

le = LabelEncoder()
# fit assigns the unique strings to numberic values.  you need this to then create dummy variables
le.fit(df['UniqueCarrier'].unique().tolist()[0:10])
#le.fit(df['TailNum].unique().tolist()[0:10])

# transform preforms the visual representation of the fit
le.transform(df['UniqueCarrier'].unique().tolist()[0:10])



array([7, 8, 9, 3, 4, 5, 6, 0, 1, 2])

In [11]:
le = LabelEncoder()

le.fit_transform(df['UniqueCarrier'].unique().tolist()[0:10])

array([7, 8, 9, 3, 4, 5, 6, 0, 1, 2])

In [7]:
le = LabelEncoder()

# way to combine 
le.fit_transform(df['TailNum'].unique().tolist()[0:10])

array([6, 9, 0, 2, 1, 7, 8, 4, 3, 5])

### TASK: How can you transform all character variables into numbers? 

+ Take 10 minutes to work with your partner

In [13]:
df2.head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime UniqueCarrier  FlightNum TailNum  ActualElapsedTime  \
0        2225            WN        335  N712SW              128.0   
1        1000            WN       3231  N772SW              128.0   
2         750            WN        448  N428WN               96.0   
3        1100            WN       1746  N612SW               88.0   
4        1925            WN       3920  N464WN               90.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay Origin Dest  Distance  TaxiIn  \
0           150.0    116.0     -14.0       8.0    IAD  TPA       810     4.0   
1           145.0    113.0       2.0      19.0    IAD  TPA       810     5.0   
2            90.0     76.0      14.0       8.0    IND  BWI       515     3.0   
3            90.0     78.0      -6.0      -4.0    IND  BWI       515     3.0   
4            90.0     77.0      34.0      34.0    IND  BWI       515     3.0   

   TaxiOut  Cancelled CancellationCode  Diverted  CarrierDelay  WeatherDelay  \
0      8.0          0                0         0           0.0           0.0   
1     10.0          0                0         0           0.0           0.0   
2     17.0          0                0         0           0.0           0.0   
3      7.0          0                0         0           0.0           0.0   
4     10.0          0                0         0           2.0           0.0   

   NASDelay  SecurityDelay  LateAircraftDelay  
0       0.0            0.0                0.0  
1       0.0            0.0                0.0  
2       0.0            0.0                0.0  
3       0.0            0.0                0.0  
4       0.0            0.0               32.0

In [35]:
df2_modified =df2[['UniqueCarrier', 'TailNum', 'Origin', 'Dest', 'CancellationCode']]
df2_modified.head()

UniqueCarrier TailNum Origin Dest CancellationCode
0            WN  N712SW    IAD  TPA                0
1            WN  N772SW    IAD  TPA                0
2            WN  N428WN    IND  BWI                0
3            WN  N612SW    IND  BWI                0
4            WN  N464WN    IND  BWI                0

In [39]:
# applies function to all rows in the dataframe
df2_modified = df2_modified.apply(lambda x: le.fit_transform(x), axis=0)

df2_modified.head()

UniqueCarrier  TailNum  Origin  Dest  CancellationCode
0              0      413      22    61                 0
1              0      470      22    61                 0
2              0      217      23    10                 0
3              0      324      23    10                 0
4              0      253      23    10                 0

In [40]:
df2[['UniqueCarrier', 'TailNum', 'Origin', 'Dest', 'CancellationCode']] = df2_modified


/Users/Carter/anaconda/lib/python2.7/site-packages/pandas/core/frame.py:2440: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]


In [42]:
df2[['UniqueCarrier', 'TailNum', 'Origin', 'Dest', 'CancellationCode']].head()

UniqueCarrier  TailNum  Origin  Dest  CancellationCode
0              0      413      22    61                 0
1              0      470      22    61                 0
2              0      217      23    10                 0
3              0      324      23    10                 0
4              0      253      23    10                 0

In [23]:
# was trying to use loop instead of lambda
for column in df2_modified:
    le = LabelEncoder()
    le.fit(df['column'].unique())
    le.transform(df.column.unique())
    

    

KeyError: 'column'

In [53]:
y = df['DepDelay']

df.drop(['DepDelay'], axis = 1, inplace = True, errors = 'ignore')

KeyError: 'DepDelay'

In [54]:
import numpy as np

(df.dtypes==np.int64).tolist()

df.dtypes

Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier          int64
FlightNum              int64
TailNum                int64
ActualElapsedTime    float64
CRSElapsedTime       float64
AirTime              float64
ArrDelay             float64
Origin                 int64
Dest                   int64
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode       int64
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

### Now as a replacement for get_dummies we have OneHotEncoder

+ BUT YOU NEED TO SPECIFY WHICH VARIABLES ARE CATEGORICAL
+ Could we use "integer" type as a proxy for that?

In [55]:
from sklearn.preprocessing import OneHotEncoder

onehot = OneHotEncoder(categorical_features = "????", sparse=True)
X =onehot.fit_transform(df)


### Note that OneHot Encoder returns a sparse matrix

+ What is a sparse matrix?

In [2]:
##This is how big the dataset is

X.shape

NameError: name 'X' is not defined

### Assignment part I - 15 minutes

+ Using a subsection of the full dataset...
    - (otherwise it will be impossibly large)
    - Create interaction variables for month and ArrDelay
    - Note that Month must first be a dummy variable
    - There are many ways to do this

### Assignment Part II

+ Run a Ridge regression with month dummies, arrival delay and the interaction vars
+ Keep track of the coefficients by saving the names to a list
+ Which variables are larger than zero? 
+ How does your model perform on the testing set?

In [64]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=0)


In [65]:
from sklearn import linear_model
lr = linear_model.Ridge(normalize=True)

In [ ]:
lr.fit(X_train, y_train)

In [ ]:
lr.score(X_test, y_test)